{
    "$type":"BloombergWebAPICore.Dto.ORequestContract",
    "RequestType":3,
    "SecurityList":[
       {
           "Identifier":"US29843LAC72",
           "IdentifierType":3,
           "GoldKey":0,
           "CrdId":"CRD_US29843LAC72"
       },
       {
           "Identifier":"XS0939678792",
           "IdentifierType":0,
           "GoldKey":3,
           "CrdId":"CRD_XS0939678792"
       },
       {
           "Identifier":"EDM6",
           "IdentifierType":0,
           "GoldKey":10,
           "CrdId":"CRD_EDM6"
       },
       {
           "Identifier":"SL3332PH",
           "IdentifierType":0,
           "GoldKey":3,
           "CrdId":"CRD_SL3332PH"
       },
       {
           "Identifier":"SL3332PH",
           "IdentifierType":2,
           "GoldKey":0,
           "CrdId":"CRD_SL3332PH"
       },
       {
           "Identifier":"912828TZ3",
           "IdentifierType":2,
           "GoldKey":0,
           "CrdId":"CRD_912828TZ3"
       },
       {
           "Identifier":"912828TZ3",
           "IdentifierType":0,
           "GoldKey":2,
           "CrdId":"CRD_912828TZ3"
       }
    ],
    "FieldsList":[
       "SW_VAL_PREMIUM",
       "SW_PAY_NOTL_AMT",
       "SW_REC_NOTL_AMT",
       "MID_PX_VAL_BP",
       "FUT_PX_VAL_BP",
       "SW_CNV_BPV"
    ]
}