{
    "SecurityData":[
       {
           "Identifier":"/ISIN/US29843LAC72",
           "SequenceNumber":0,
           "CrdId":"CRD_US29843LAC72",
           "FieldList":null,
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"XS0939678792 Corp",
           "SequenceNumber":1,
           "CrdId":"CRD_XS0939678792",
           "FieldList":null,
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to security",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"EDM6 Index",
           "SequenceNumber":2,
           "CrdId":"CRD_EDM6",
           "FieldList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "FieldValue":"0.0025"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"SL3332PH Corp",
           "SequenceNumber":3,
           "CrdId":"CRD_SL3332PH",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"70022609"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"3025000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"3025000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"7245788"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SL3332PH",
           "SequenceNumber":4,
           "CrdId":"CRD_SL3332PH",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"70022609"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"3025000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"3025000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"7245788"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/912828TZ3",
           "SequenceNumber":5,
           "CrdId":"CRD_912828TZ3",
           "FieldList":null,
           "FieldExceptionList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"912828TZ3 Govt",
           "SequenceNumber":6,
           "CrdId":"CRD_912828TZ3",
           "FieldList":null,
           "FieldExceptionList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SP8A1ETA",
           "SequenceNumber":7,
           "CrdId":"CRD_SP8A1ETA",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"96007"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"10000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"10000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"-4090.24948928462"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SP3A0TU1",
           "SequenceNumber":8,
           "CrdId":"CRD_SP3A0TU1",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"10853"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"10000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"10000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"-4497.18720377742"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SP4A102V",
           "SequenceNumber":9,
           "CrdId":"CRD_SP4A102V",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"1069953"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"10000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"10000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"4704.90132446361"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"978::bbdbl29",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SL7B04GS",
           "SequenceNumber":10,
           "CrdId":"CRD_SL7B04GS",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"77403.6092310925"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"548800000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"548800000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"110569.242882357"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"927::bbdbl2",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SLQF01NK",
           "SequenceNumber":11,
           "CrdId":"CRD_SLQF01NK",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"5255477"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"106000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"106000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"257852"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"927::bbdbl2",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SL6A2LTR",
           "SequenceNumber":12,
           "CrdId":"CRD_SL6A2LTR",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"1111340.00022987"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"23400000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"23400000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"-17121.6940054464"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"927::bbdbl2",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SL602VFM",
           "SequenceNumber":13,
           "CrdId":"CRD_SL602VFM",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"0"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"110000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"110000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"0"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"927::bbdbl2",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SL602VFS",
           "SequenceNumber":14,
           "CrdId":"CRD_SL602VFS",
           "FieldList":[
              {
                  "FieldId":"SW_VAL_PREMIUM",
                  "FieldValue":"0"
              },
              {
                  "FieldId":"SW_PAY_NOTL_AMT",
                  "FieldValue":"650000000"
              },
              {
                  "FieldId":"SW_REC_NOTL_AMT",
                  "FieldValue":"650000000"
              },
              {
                  "FieldId":"SW_CNV_BPV",
                  "FieldValue":"0"
              }
           ],
           "FieldExceptionList":[
              {
                  "FieldId":"FUT_PX_VAL_BP",
                  "ErrorInfo":{
                      "Source":"927::bbdbl2",
                      "Code":9,
                      "Category":"BAD_FLD",
                      "Message":"Field not applicable to product",
                      "Subcategory":"NOT_APPLICABLE_TO_REF_DATA"
                  }
              }
           ],
           "SecurityError":null
       },
       {
           "Identifier":"/CUSIP/SL602",
           "SequenceNumber":15,
           "CrdId":"CRD_SL602",
           "FieldList":null,
           "FieldExceptionList":null,
           "SecurityError":{
               "Source":"927::bbdbl2",
               "Code":15,
               "Category":"BAD_SEC",
               "Message":"Unknown/Invalid security [nid:927] ",
               "Subcategory":"INVALID_SECURITY"
           }
       },
       {
           "Identifier":"XS0939678 Corp",
           "SequenceNumber":16,
           "CrdId":"CRD_XS0939678792",
           "FieldList":null,
           "FieldExceptionList":null,
           "SecurityError":{
               "Source":"927::bbdbl2",
               "Code":15,
               "Category":"BAD_SEC",
               "Message":"Unknown/Invalid security [nid:927] ",
               "Subcategory":"INVALID_SECURITY"
           }
       }
    ],
    "OrigRequest":{
        "$type":"BloombergWebAPICore.Dto.ORequestContract",
        "RequestType":3,
        "SecurityList":[
           {
               "Identifier":"US29843LAC72",
               "IdentifierType":3,
               "GoldKey":0,
               "CrdId":"CRD_US29843LAC72"
           },
           {
               "Identifier":"XS0939678792",
               "IdentifierType":0,
               "GoldKey":3,
               "CrdId":"CRD_XS0939678792"
           },
           {
               "Identifier":"EDM6",
               "IdentifierType":0,
               "GoldKey":10,
               "CrdId":"CRD_EDM6"
           },
           {
               "Identifier":"SL3332PH",
               "IdentifierType":0,
               "GoldKey":3,
               "CrdId":"CRD_SL3332PH"
           },
           {
               "Identifier":"SL3332PH",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SL3332PH"
           },
           {
               "Identifier":"912828TZ3",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_912828TZ3"
           },
           {
               "Identifier":"912828TZ3",
               "IdentifierType":0,
               "GoldKey":2,
               "CrdId":"CRD_912828TZ3"
           },
           {
               "Identifier":"SP8A1ETA",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SP8A1ETA"
           },
           {
               "Identifier":"SP3A0TU1",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SP3A0TU1"
           },
           {
               "Identifier":"SP4A102V",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SP4A102V"
           },
           {
               "Identifier":"SL7B04GS",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SL7B04GS"
           },
           {
               "Identifier":"SLQF01NK",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SLQF01NK"
           },
           {
               "Identifier":"SL6A2LTR",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SL6A2LTR"
           },
           {
               "Identifier":"SL602VFM",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SL602VFM"
           },
           {
               "Identifier":"SL602VFS",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SL602VFS"
           },
           {
               "Identifier":"SL602",
               "IdentifierType":2,
               "GoldKey":0,
               "CrdId":"CRD_SL602"
           },
           {
               "Identifier":"US29843LAC72",
               "IdentifierType":0,
               "GoldKey":0,
               "CrdId":"CRD_US29843LAC72"
           },
           {
               "Identifier":"XS0939678",
               "IdentifierType":0,
               "GoldKey":3,
               "CrdId":"CRD_XS0939678792"
           }
        ],
        "FieldsList":[
           "SW_VAL_PREMIUM",
           "SW_PAY_NOTL_AMT",
           "SW_REC_NOTL_AMT",
           "FUT_PX_VAL_BP",
           "SW_CNV_BPV"
        ]
    },
   "RequestError":{
       "Source":"US29843LAC72",
       "Code":0,
       "Category":"none",
       "Message":"US29843LAC72 not given a goldkey or indentifier type",
       "Subcategory":""
   },
   "ResponseError":null
}